Class {
	#name : 'MyChessBlackSquare',
	#superclass : 'MyChessSquare',
	#category : 'Myg-Chess-Core',
	#package : 'Myg-Chess-Core'
}

{ #category : 'rendering' }
MyChessBlackSquare >> renderBlackBishop [ [ 
	
	^ 'v' 
	
]
]

{ #category : 'rendering' }
MyChessBlackSquare >> renderBlackKing [ [ 
	
	^ 'l' 
	
]
]

{ #category : 'rendering' }
MyChessBlackSquare >> renderBlackKnight [ [ 
	
	^ 'm' 
	
]
]

{ #category : 'rendering' }
MyChessBlackSquare >> renderBlackPawn [ [ 
	
	^ 'o' 
	
]
]

{ #category : 'rendering' }
MyChessBlackSquare >> renderBlackQueen [ [ 
	
	^ 'w' 
	
]
]

{ #category : 'rendering' }
MyChessBlackSquare >> renderBlackRook [ [ 
	
	^ 't' 
	
]
]

{ #category : 'rendering' }
MyChessBlackSquare >> renderWhiteBishop [ [ 
	
	^ 'b' 
	
]
]

{ #category : 'rendering' }
MyChessBlackSquare >> renderWhiteKing [ [ 
	
	^ 'k' 
	
]
]

{ #category : 'rendering' }
MyChessBlackSquare >> renderWhiteKnight [ [ 
	
	^ 'n' 
	
]
]

{ #category : 'rendering' }
MyChessBlackSquare >> renderWhitePawn [ [ 
	
	^ 'p' 
	
]
]

{ #category : 'rendering' }
MyChessBlackSquare >> renderWhiteQueen [ [ 
	
	^ 'q' 
	
]
]

{ #category : 'rendering' }
MyChessBlackSquare >> renderWhiteRook [ [ 
	
	^ 'r' 
	
]
]
